;    ATTOLISP.ASM
;
;    6502 ASSEMBLER IMPLEMENTATION OF A LISP TOO SMALL TO USE
;
;
R0   	=	$02             ; REGISTERS
R0H     =   $02
R0L     =   $03
R1   	=	$04
R1H     =   $04
R1L     =   $05
R2   	=	$06
R2H     =   $06
R2L     =   $07
R3   	=	$08
R3H     =   $08
R3L     =   $09

RSLT    =   $0A             ; RESULT LOCATION
RSLTH   =   $0A
RSLTL   =   $0B
CRRNT 	=	$0C             ; CURRENT SCOPE POINTER
CRRNTH  =   $0C
CRRNTL  =   $0D
SPTR	=	$12				; S-EXPRESSION SPACE POINTER
SPTRH	=	$12
SPTRL	=	$13
CPTR	=	$14				; SCOPE SPACE POINTER
CPTRH	=	$14
CPTRL	=	$15
QPTR	=	$16				; QUOTE SPACE POINTER
QPTRH	=	$16
QPTHL	=	$17
FPTR	=	$18				; FUNCTION SPACE POINTER
FPTRH	=	$18
FPTRL	=	$19
MPTR	=	$1A				; MACRO SPACE POINTER
MPTRH	=	$1A
MPTRL	=	$1B
INPTR	=	$1C				; INPUT POINTER
INPTRH	=	$1C
INPTRL	=	$1D
OTPTR	=	$1E				; OUTPUT POINTER
OTPTRH	=	$1E
OTPTRL	=	$1F

ENDPGE  =   $FF             ; END OF ANY PAGE

; STACK POINTER USES PAGE 1

XSPCE	=	$0200			; START OF S-EXPRESSION SPACE
SCOPES  =   $3C00           ; START OF SCOPE SPACE
QPTRS	=	$C000			; START OF QUOTE POINTERS SPACE
FNS		=	$D000			; START OF FUNCTION SPACE
MACROS	=	$F000			; START OF MACRO SPACE
INPUT   =   $F800           ; INPUT
OUTPUT 	=   $FA00           ; OUPUT START
OUTLP	=	$FC				; OUTPUT AFTER LAST PAGE

SCPSZ   =   52              ; SIZE OF SCOPE (2 * 26 LETTERS)
SCPLMT	=	203				; LIMIT OF SCOPE ON ONE PAGE

*       =   $FC00

        LDA #0
        
;  SETUP GLOBAL SCOPE

        STA *CRRNTH
        LDX #>SCOPES
        STX *CRRNTL

; CLEAR GLOBAL SCOPE

		LDY	#SCPSZ
CLGSL	DEY
		STA ($CRRNT),Y
		BNE	CLGSL

; SETUP OUTPUT POINTER AND SET SPACE TO BLANK

        STA *OTPTRH
        STA *R0H
        LDX #>OUTPUT
        STX *OTPTRL
        STX *R0L
		
		LDA	#$20
CLOUTL	STA (R0),Y
		INY
		BNE	CLOUTL
		INX
		CPX	#OUTLP
		BEQ	DONE				; TEMPORARY
		STX	*R0L
		BNE	CLOUTL

;  FINISH

DONE    BRK
        
; CLEAR SPACE SUBROUTINE
; ACCUMULATOR CONTAINS VALUE
; R0 POINTS TO START
; R1 POINTS TO END

