; Section 1.2
; ===========

#|
Exercise 1.9
============

Each of the following two procedures defines a method for adding two positive
integers in terms of the procedures inc, which increments its argument by 1,
and dec, which decrements its argument by 1.

(define (+ a b)
  (if (= a 0) 
      b 
      (inc (+ (dec a) b))))

(define (+ a b)
  (if (= a 0) 
      b 
      (+ (dec a) (inc b))))

Using the substitution model, illustrate the process generated by each procedure in
evaluating (+ 3 2). Are these processes iterative or recursive?

Answer
======
NB: I've cheated a bit and decreased the arguments from (+ 4 5) to (+ 2  3). I'm a busy
person.

First version
-------------
Generates a process that looks like this:

(inc (+ (dec 3) 2)
(inc (+ (dec (dec 3)) 2)
(inc (+ (dec (dec (dec 3))) 2)

This is a recursive procedure because it is storing the number of times to apply '+' to
2 in the stack.

Second version
--------------
(+ (dec 3) (inc 2))
(+ (dec (dec 3)) (inc (inc 2))
(+ (dec (dec (dec 3))) (inc (inc (inc 2)))

Even though the second version has nested dec and inc calls, this is an iterative process,
because there is no information about the state of the computation stored in the stack. 
|#


#|

Exercise 1.10
=============
The following procedure computes a mathematical function called Ackermann’s function.
|#

(define (A x y)
  (cond ((= y 0) 0)
        ((= x 0) (* 2 y))
        ((= y 1) 2)
        (else (A (- x 1)
                 (A x (- y 1))))))

; What are the values of the following expressions?


(display "(A 1 10):")
(A 1 10)
(display "(A 2 4):")
(A 2 4)
(display "(A 3 3):")
(A 3 3)


#|
; Consider the following procedures, where A is the procedure defined above:

Give concise mathematical definitions for the functions computed by the procedures f, g,
and h for positive integer values of n . For example, (k n) computes 5 n 2.|#


(define (f n) (A 0 n))
(f 0)
(f 1)
(f 2)
(f 3)
(f 4)
(f 5)
(f 10)
(f 6.6)
(f -5.5)
; 2 * n
(define (g n) (A 1 n))
(g 0)
(g 1)
(g 2)
(g 3)
(g 4)
(g 5)
(g 10)
; (g 6.6) does not terminate
; (g -5) does note terminate
; 2 ^ n

(define (h n) (A 2 n))
(h 1)
(h 2)
(h 3)
(h 4)
; negative and floats do not terminate
; 2^2^2...n times, (Knuth up arrow).


