Chez Scheme Version 9.5.3
Copyright 1984-2019 Cisco Systems, Inc.

> (require "paip-1.scm")

Exception: variable require is not bound
Type (debug) to enter the debugger.
> (load "paip-1.scm")
> (run 1 (q)
    (+o (build-num 6) (build-num 7) q))

Exception: variable \x2B;o is not bound
Type (debug) to enter the debugger.
> +o

Exception: variable \x2B;o is not bound
Type (debug) to enter the debugger.
> pluso
#<procedure pluso at numbers.scm:1846>
> (run 1 (q)
    (pluso (build-num 6) (build-num 7) q))
((1 0 1 1))
> (run 1 (q)
    (pluso (build-num 6)
           (build-num 7)
           '(1 0 1 1)))
(_.0)
> (run* (x y)
    (pluso x
           y
           '(1 0 1 1)))
(((1 0 1 1) ())
 (() (1 0 1 1))
 ((1) (0 0 1 1))
 ((0 0 1 1) (1))

  ((1 1) (0 1 0 1)) ((0 1) (1 1 0 1)) ((1 1 1) (0 1 1))
  ((0 1 1) (1 1 1)) ((1 1 0 1) (0 1)) ((0 1 0 1) (1 1))
  ((1 0 1) (0 0 0 1)) ((0 0 1) (1 0 0 1)) ((1 0 0 1) (0 0 1))
  ((0 0 0 1) (1 0 1)))
> (run 1 (q)
    (count-anywhereo '(x y) '((z x y) ((x y z) b) x y)))

Exception: incorrect number of arguments to #<procedure count-anywhereo at paip-1.scm:458>
Type (debug) to enter the debugger.
> (load "paip-1.scm")
> (run 1 (q)
    (count-anywhereo
     '(x y)
     '((z x y) ((x y z) b) x y)
     (build-num 2)))
()
> (run 1 (q)
    (count-anywhereo
     '(x y)
     '((z x y) ((x y z) b) x y)
     q))
  C-c C-c
break> r
> (run 1 (q)
    (count-anywhereo
     '(x y)
     '((z x y) ((x y z) b) x y)
     q))
  C-c C-c
break> r
> (load "paip-1.scm")
> (run 1 (q)
    (count-anywhereo
     '(x y)
     '((z x y) ((x y z) b) x y)
     q))
()
> (load "paip-1.scm")
> (run 1 (q)
    (count-anywhereo
     '(x y)
     '((z x y) ((x y z) b) x y)
     q))
((0 1))
> (run 1 (q)
    (count-anywhereo
     q
     '((z x y) ((x y z) b) x y)
     (build-num 2)))
((x y))
> (run 2 (q)
    (count-anywhereo
     q
     '((z x y) ((x y z) b) x y)
     (build-num 2)))
((x y) z)
> (run 3 (q)
    (count-anywhereo
     q
     '((z x y) ((x y z) b) x y)
     (build-num 2)))
((x y) z (y))
> (run 4 (q)
    (count-anywhereo
     q
     '((z x y) ((x y z) b) x y)
     (build-num 2)))
((x y) z (y))
> (run* (q)
    (count-anywhereo
     q
     '((z x y) ((x y z) b) x y)
     (build-num 2)))
((x y) z (y))
> (run 1 (e1 e2)
    (count-anywhereo
     e1
     e2
     (build-num 3)))
((_.0 (_.0 _.0 . _.0)))
> (run 100 (e1 e2)
    (count-anywhereo
     e1
     e2
     (build-num 3)))
((_.0 (_.0 _.0 . _.0)) ((_.0 (_.0 _.0 _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 () . _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 _.0 . #t)) (=/= ((_.0 #t))))
 ((_.0 (_.0 _.0 _.0 . #f)) (=/= ((_.0 #f))))
 ((_.0 (_.0 () _.0 . _.0)) (=/= ((_.0 ()))))
 ((_.0 (() _.0 _.0 . _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 _.0 . _.1)) (=/= ((_.0 _.1))) (sym _.1))
 ((_.0 (_.0 _.0 #t . _.0)) (=/= ((_.0 #t))))
 ((_.0 (_.0 _.0 _.0 . _.1)) (=/= ((_.0 _.1))) (num _.1))
 ((_.0 (_.0 #t _.0 . _.0)) (=/= ((_.0 #t))))
 ((_.0 (_.0 _.0 #f . _.0)) (=/= ((_.0 #f))))
 (_.0 ((_.0 . _.0) . _.0))
 ((_.0 (#t _.0 _.0 . _.0)) (=/= ((_.0 #t))))
 ((_.0 (_.0 _.0 _.1 . _.0)) (=/= ((_.0 _.1))) (sym _.1))
 ((_.0 (_.0 #f _.0 . _.0)) (=/= ((_.0 #f))))
 ((_.0 (_.0 _.0 () _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 _.0 ())) (=/= ((_.0 (()))) ((_.0 ()))))
 ((_.0 (#f _.0 _.0 . _.0)) (=/= ((_.0 #f))))
 ((_.0 (_.0 () _.0 _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 () () . _.0)) (=/= ((_.0 ()))))
 ((_.0 (() _.0 _.0 _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 _.0 () . #t))
   (=/= ((_.0 (() . #t))) ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.0 _.0 () _.0 . #t)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.0 () _.0 () . _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 _.1 . _.0)) (=/= ((_.0 _.1))) (num _.1))
 ((_.0 (_.0 _.0 _.0 () . #f))
   (=/= ((_.0 (() . #f))) ((_.0 #f)) ((_.0 ()))))
 ((_.0 (_.0 () _.0 _.0 . #t)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (() _.0 _.0 () . _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 () _.0 . #f)) (=/= ((_.0 #f)) ((_.0 ()))))
 ((_.0 (_.0 _.1 _.0 . _.0)) (=/= ((_.0 _.1))) (sym _.1))
 ((_.0 (() _.0 _.0 _.0 . #t)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.0 _.0 _.0 #t))
   (=/= ((_.0 (#t))) ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.0 _.0 _.0 () . _.1))
   (=/= ((_.0 (() . _.1))) ((_.0 _.1)) ((_.0 ())))
   (sym _.1))
 ((_.0 (_.0 () _.0 _.0 . #f)) (=/= ((_.0 #f)) ((_.0 ()))))
 ((_.0 (_.0 _.0 () _.0 . _.1))
   (=/= ((_.0 _.1)) ((_.0 ())))
   (sym _.1))
 ((_.0 (_.0 () () _.0 . _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 () #t . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (() _.0 _.0 _.0 . #f)) (=/= ((_.0 #f)) ((_.0 ()))))
 ((_.0 (_.0 _.0 #t _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (() _.0 () _.0 . _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 () _.0 _.0 . _.1))
   (=/= ((_.0 _.1)) ((_.0 ())))
   (sym _.1))
 ((_.0 (_.0 _.0 _.0 () . _.1))
   (=/= ((_.0 (() . _.1))) ((_.0 _.1)) ((_.0 ())))
   (num _.1))
 ((_.0 (_.0 () _.0 #t . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (() () _.0 _.0 . _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 () _.0 . _.1))
   (=/= ((_.0 _.1)) ((_.0 ())))
   (num _.1))
 ((_.0 (() _.0 _.0 _.0 . _.1))
   (=/= ((_.0 _.1)) ((_.0 ())))
   (sym _.1))
 ((_.0 (_.0 _.0 _.0 #t . #t))
   (=/= ((_.0 (#t . #t))) ((_.0 #t))))
 ((_.0 (() _.0 _.0 #t . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.0 #t _.0 _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.0 _.0 #t () . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.1 _.0 _.0 . _.0)) (=/= ((_.0 _.1))) (sym _.1))
 ((_.0 (_.0 () _.0 _.0 . _.1))
   (=/= ((_.0 _.1)) ((_.0 ())))
   (num _.1))
 ((_.0 (_.0 _.0 #t _.0 . #t)) (=/= ((_.0 #t))))
 ((_.0 (_.0 (_.0 . _.0))) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 _.0 #t . #f))
   (=/= ((_.0 (#t . #f))) ((_.0 #f)) ((_.0 #t))))
 ((_.0 (() _.0 _.0 _.0 . _.1))
   (=/= ((_.0 _.1)) ((_.0 ())))
   (num _.1))
 ((_.0 ((_.0 . _.0) _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 #t _.0 () . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (#t _.0 _.0 _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.0 _.0 #t _.0 . #f)) (=/= ((_.0 #f)) ((_.0 #t))))
 ((_.0 (_.0 _.0 () #f . _.0)) (=/= ((_.0 #f)) ((_.0 ()))))
 ((_.0 (_.0 _.0 _.0 #f))
   (=/= ((_.0 (#f))) ((_.0 #f)) ((_.0 ()))))
 ((_.0 (_.0 #t _.0 _.0 . #t)) (=/= ((_.0 #t))))
 ((_.0 (_.0 _.0 _.0 #t . _.1))
   (=/= ((_.0 (#t . _.1))) ((_.0 #t)) ((_.0 _.1)))
   (sym _.1))
 ((_.0 (_.0 (_.0 . _.0) . #t)) (=/= ((_.0 #t))))
 ((_.0 (_.0 _.1 _.0 . _.0)) (=/= ((_.0 _.1))) (num _.1))
 ((_.0 (_.0 () #t _.0 . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (#t _.0 _.0 () . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.0 (_.0) . _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 () _.0 #f . _.0)) (=/= ((_.0 #f)) ((_.0 ()))))
 ((_.0 ((_.0 . _.0) () . _.0)) (=/= ((_.0 ()))))
 ((_.0 (() _.0 #t _.0 . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.0 _.0 #t _.0 . _.1))
   (=/= ((_.0 #t)) ((_.0 _.1)))
   (sym _.1))
 ((_.0 (_.0 _.0 #t #t . _.0)) (=/= ((_.0 #t))))
 ((_.0 (#t _.0 _.0 _.0 . #t)) (=/= ((_.0 #t))))
 ((_.0 (() _.0 _.0 #f . _.0)) (=/= ((_.0 #f)) ((_.0 ()))))
 ((_.0 (_.0 _.0 _.0 #t . _.1))
   (=/= ((_.0 (#t . _.1))) ((_.0 #t)) ((_.0 _.1)))
   (num _.1))
 ((_.0 (_.0 _.0 #f _.0)) (=/= ((_.0 #f)) ((_.0 ()))))
 ((_.0 (_.0 #t _.0 _.0 . #f)) (=/= ((_.0 #f)) ((_.0 #t))))
 ((_.0 ((_.0 . _.0) _.0 . #t)) (=/= ((_.0 #t))))
 ((_.0 (_.0 (_.0 . _.0) . #f)) (=/= ((_.0 #f))))
 ((_.0 (_.0 #t () _.0 . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (() (_.0 . _.0) . _.0)) (=/= ((_.0 ()))))
 ((_.0 (#t _.0 _.0 _.0 . #f)) (=/= ((_.0 #f)) ((_.0 #t))))
 ((_.0 (_.0 _.0 _.0 #f . #t))
   (=/= ((_.0 (#f . #t))) ((_.0 #f)) ((_.0 #t))))
 ((_.0 (_.0 #t _.0 _.0 . _.1))
   (=/= ((_.0 #t)) ((_.0 _.1)))
   (sym _.1))
 ((_.0 (_.0 _.0 #t _.0 . _.1))
   (=/= ((_.0 #t)) ((_.0 _.1)))
   (num _.1))
 ((_.0 (#t _.0 () _.0 . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 (_.0 (_.0 . _.0) . _.1)) (=/= ((_.0 _.1))) (sym _.1))
 ((_.0 (_.0 #t _.0 #t . _.0)) (=/= ((_.0 #t))))
 ((_.0 (() #t _.0 _.0 . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 ((_.0 . _.0) _.0 . #f)) (=/= ((_.0 #f))))
 ((_.0 (_.0 _.0 #f () . _.0)) (=/= ((_.0 #f)) ((_.0 ()))))
 ((_.0 (#t () _.0 _.0 . _.0)) (=/= ((_.0 #t)) ((_.0 ()))))
 ((_.0 ((_.0) _.0 . _.0)) (=/= ((_.0 ()))))
 ((_.0 (_.0 _.0 _.0 #f . #f))
   (=/= ((_.0 (#f . #f))) ((_.0 #f))))
 ((_.0 (_.0 #f _.0 _.0)) (=/= ((_.0 #f)) ((_.0 ()))))
 ((_.0 (#t _.0 _.0 _.0 . _.1))
   (=/= ((_.0 #t)) ((_.0 _.1)))
   (sym _.1))
 ((_.0 (_.0 _.0 #f _.0 . #t)) (=/= ((_.0 #f)) ((_.0 #t)))))
> (run* (q)
    (count-anywhereo
     q
     '((z x y) ((x y z) b) x y)
     (build-num 2)))
((x y) z (y))
> 

Process scheme finished
Chez Scheme Version 9.5.3
Copyright 1984-2019 Cisco Systems, Inc.

> (random 100)
7
> 

Process scheme finished
Chez Scheme Version 9.5.3
Copyright 1984-2019 Cisco Systems, Inc.

> (load "paip-1.scm")
> membero

Exception: variable membero is not bound
Type (debug) to enter the debugger.
> (load "paip-1.scm")
> (run 1 (q) (sentence q))
(((the man) (hit (the man))))
> (run 10 (q) (sentence q))
(((the man) (hit (the man))) ((the man) (hit (the ball))) ((the man) (hit (a man)))
  ((the man) (took (the man))) ((the ball) (hit (the man)))
  ((the man) (hit (the woman))) ((the man) (hit (a ball)))
  ((the man) (hit (the table))) ((the man) (hit (a woman)))
  ((the man) (took (the ball))))
> (run 100 (q) (sentence q))
(((the man) (hit (the man))) ((the man) (hit (the ball)))
 ((the man) (hit (a man))) ((the man) (took (the man)))
 ((the ball) (hit (the man))) ((the man) (hit (the woman)))
 ((the man) (hit (a ball))) ((the man) (hit (the table)))
 ((the man) (hit (a woman))) ((the man) (took (the ball)))
 ((the man) (hit (a table))) ((the ball) (hit (the ball)))
 ((the man) (took (a man))) ((the ball) (hit (a man)))
 ((the man) (saw (the man))) ((a man) (hit (the man)))
 ((the man) (took (the woman))) ((the man) (took (a ball)))
 ((the ball) (took (the man))) ((the man) (liked (the man)))
 ((the man) (took (the table)))
 ((the ball) (hit (the woman))) ((the man) (took (a woman)))
 ((the ball) (hit (a ball))) ((the man) (saw (the ball)))
 ((the man) (took (a table))) ((the man) (saw (a man)))
 ((the man) (liked (the ball))) ((the man) (liked (a man)))
 ((the man) (saw (the woman))) ((the man) (saw (a ball)))
 ((the ball) (hit (the table))) ((the ball) (hit (a woman)))
 ((the man) (liked (the woman))) ((the man) (liked (a ball)))
 ((the man) (saw (the table))) ((a man) (hit (the ball)))
 ((the man) (saw (a woman))) ((the ball) (took (the ball)))
 ((the man) (liked (the table)))
 ((the man) (liked (a woman))) ((a man) (hit (a man)))
 ((the man) (saw (a table))) ((the ball) (hit (a table)))
 ((the ball) (took (a man))) ((the man) (liked (a table)))
 ((the ball) (saw (the man))) ((a man) (took (the man)))
 ((the ball) (took (the woman))) ((the ball) (took (a ball)))
 ((the woman) (hit (the man))) ((a man) (hit (the woman)))
 ((the ball) (liked (the man))) ((a man) (hit (a ball)))
 ((the ball) (took (the table)))
 ((the ball) (took (a woman))) ((the ball) (saw (the ball)))
 ((the ball) (took (a table))) ((the ball) (saw (a man)))
 ((the ball) (liked (the ball))) ((the ball) (liked (a man)))
 ((a man) (hit (the table))) ((the ball) (saw (the woman)))
 ((a man) (hit (a woman))) ((the ball) (saw (a ball)))
 ((the ball) (liked (the woman)))
 ((the ball) (liked (a ball))) ((a man) (took (the ball)))
 ((the ball) (saw (the table))) ((the ball) (saw (a woman)))
 ((the woman) (hit (the ball))) ((a man) (hit (a table)))
 ((the ball) (liked (the table))) ((a man) (took (a man)))
 ((the ball) (liked (a woman))) ((the ball) (saw (a table)))
 ((the woman) (hit (a man))) ((the ball) (liked (a table)))
 ((a man) (saw (the man))) ((a ball) (hit (the man)))
 ((a man) (took (the woman))) ((the woman) (took (the man)))
 ((a man) (took (a ball))) ((a man) (liked (the man)))
 ((the woman) (hit (the woman))) ((a man) (took (the table)))
 ((a man) (took (a woman))) ((the woman) (hit (a ball)))
 ((a man) (saw (the ball))) ((a man) (took (a table)))
 ((a man) (saw (a man))) ((a man) (liked (the ball)))
 ((a man) (liked (a man))) ((a man) (saw (the woman)))
 ((the woman) (hit (the table))) ((a man) (saw (a ball)))
 ((the woman) (hit (a woman))) ((a man) (liked (the woman)))
 ((a man) (liked (a ball))) ((a man) (saw (the table))))
> 

Process scheme finished
Chez Scheme Version 9.5.3
Copyright 1984-2019 Cisco Systems, Inc.

> (load "paip-1.scm")
> (run 100 (q) (sentence q))
(((the man) hit the man) ((the man) hit the ball)
 ((the man) hit a man) ((the man) took the man)
 ((the ball) hit the man) ((the man) hit the woman)
 ((the man) hit a ball) ((the man) hit the table)
 ((the man) hit a woman) ((the man) took the ball)
 ((the man) hit a table) ((the ball) hit the ball)
 ((the man) took a man) ((the ball) hit a man)
 ((the man) saw the man) ((a man) hit the man)
 ((the man) took the woman) ((the man) took a ball)
 ((the ball) took the man) ((the man) liked the man)
 ((the man) took the table) ((the ball) hit the woman)
 ((the man) took a woman) ((the ball) hit a ball)
 ((the man) saw the ball) ((the man) took a table)
 ((the man) saw a man) ((the man) liked the ball)
 ((the man) liked a man) ((the man) saw the woman)
 ((the man) saw a ball) ((the ball) hit the table)
 ((the ball) hit a woman) ((the man) liked the woman)
 ((the man) liked a ball) ((the man) saw the table)
 ((a man) hit the ball) ((the man) saw a woman)
 ((the ball) took the ball) ((the man) liked the table)
 ((the man) liked a woman) ((a man) hit a man)
 ((the man) saw a table) ((the ball) hit a table)
 ((the ball) took a man) ((the man) liked a table)
 ((the ball) saw the man) ((a man) took the man)
 ((the ball) took the woman) ((the ball) took a ball)
 ((the woman) hit the man) ((a man) hit the woman)
 ((the ball) liked the man) ((a man) hit a ball)
 ((the ball) took the table) ((the ball) took a woman)
 ((the ball) saw the ball) ((the ball) took a table)
 ((the ball) saw a man) ((the ball) liked the ball)
 ((the ball) liked a man) ((a man) hit the table)
 ((the ball) saw the woman) ((a man) hit a woman)
 ((the ball) saw a ball) ((the ball) liked the woman)
 ((the ball) liked a ball) ((a man) took the ball)
 ((the ball) saw the table) ((the ball) saw a woman)
 ((the woman) hit the ball) ((a man) hit a table)
 ((the ball) liked the table) ((a man) took a man)
 ((the ball) liked a woman) ((the ball) saw a table)
 ((the woman) hit a man) ((the ball) liked a table)
 ((a man) saw the man) ((a ball) hit the man)
 ((a man) took the woman) ((the woman) took the man)
 ((a man) took a ball) ((a man) liked the man)
 ((the woman) hit the woman) ((a man) took the table)
 ((a man) took a woman) ((the woman) hit a ball)
 ((a man) saw the ball) ((a man) took a table)
 ((a man) saw a man) ((a man) liked the ball)
 ((a man) liked a man) ((a man) saw the woman)
 ((the woman) hit the table) ((a man) saw a ball)
 ((the woman) hit a woman) ((a man) liked the woman)
 ((a man) liked a ball) ((a man) saw the table))
> 

Process scheme finished
Chez Scheme Version 9.5.3
Copyright 1984-2019 Cisco Systems, Inc.

> (load "paip-1.scm")
> (run 100 (q) (sentence q))
((the man hit the man) (the man hit the ball)
 (the man hit a man) (the man took the man)
 (the ball hit the man) (the man hit the woman)
 (the man hit a ball) (the man hit the table)
 (the man hit a woman) (the man took the ball)
 (the man hit a table) (the ball hit the ball)
 (the man took a man) (the ball hit a man)
 (the man saw the man) (a man hit the man)
 (the man took the woman) (the man took a ball)
 (the ball took the man) (the man liked the man)
 (the man took the table) (the ball hit the woman)
 (the man took a woman) (the ball hit a ball)
 (the man saw the ball) (the man took a table)
 (the man saw a man) (the man liked the ball)
 (the man liked a man) (the man saw the woman)
 (the man saw a ball) (the ball hit the table)
 (the ball hit a woman) (the man liked the woman)
 (the man liked a ball) (the man saw the table)
 (a man hit the ball) (the man saw a woman)
 (the ball took the ball) (the man liked the table)
 (the man liked a woman) (a man hit a man)
 (the man saw a table) (the ball hit a table)
 (the ball took a man) (the man liked a table)
 (the ball saw the man) (a man took the man)
 (the ball took the woman) (the ball took a ball)
 (the woman hit the man) (a man hit the woman)
 (the ball liked the man) (a man hit a ball)
 (the ball took the table) (the ball took a woman)
 (the ball saw the ball) (the ball took a table)
 (the ball saw a man) (the ball liked the ball)
 (the ball liked a man) (a man hit the table)
 (the ball saw the woman) (a man hit a woman)
 (the ball saw a ball) (the ball liked the woman)
 (the ball liked a ball) (a man took the ball)
 (the ball saw the table) (the ball saw a woman)
 (the woman hit the ball) (a man hit a table)
 (the ball liked the table) (a man took a man)
 (the ball liked a woman) (the ball saw a table)
 (the woman hit a man) (the ball liked a table)
 (a man saw the man) (a ball hit the man)
 (a man took the woman) (the woman took the man)
 (a man took a ball) (a man liked the man)
 (the woman hit the woman) (a man took the table)
 (a man took a woman) (the woman hit a ball)
 (a man saw the ball) (a man took a table) (a man saw a man)
 (a man liked the ball) (a man liked a man)
 (a man saw the woman) (the woman hit the table)
 (a man saw a ball) (the woman hit a woman)
 (a man liked the woman) (a man liked a ball)
 (a man saw the table))
> (run 1000 (q) (sentence q))
((the man hit the man) (the man hit the ball)
 (the man hit a man) (the man took the man)
 (the ball hit the man) (the man hit the woman)
 (the man hit a ball) (the man hit the table)
 (the man hit a woman) (the man took the ball)
 (the man hit a table) (the ball hit the ball)
 (the man took a man) (the ball hit a man)
 (the man saw the man) (a man hit the man)
 (the man took the woman) (the man took a ball)
 (the ball took the man) (the man liked the man)
 (the man took the table) (the ball hit the woman)
 (the man took a woman) (the ball hit a ball)
 (the man saw the ball) (the man took a table)
 (the man saw a man) (the man liked the ball)
 (the man liked a man) (the man saw the woman)
 (the man saw a ball) (the ball hit the table)
 (the ball hit a woman) (the man liked the woman)
 (the man liked a ball) (the man saw the table)
 (a man hit the ball) (the man saw a woman)
 (the ball took the ball) (the man liked the table)
 (the man liked a woman) (a man hit a man)
 (the man saw a table) (the ball hit a table)
 (the ball took a man) (the man liked a table)
 (the ball saw the man) (a man took the man)
 (the ball took the woman) (the ball took a ball)
 (the woman hit the man) (a man hit the woman)
 (the ball liked the man) (a man hit a ball)
 (the ball took the table) (the ball took a woman)
 (the ball saw the ball) (the ball took a table)
 (the ball saw a man) (the ball liked the ball)
 (the ball liked a man) (a man hit the table)
 (the ball saw the woman) (a man hit a woman)
 (the ball saw a ball) (the ball liked the woman)
 (the ball liked a ball) (a man took the ball)
 (the ball saw the table) (the ball saw a woman)
 (the woman hit the ball) (a man hit a table)
 (the ball liked the table) (a man took a man)
 (the ball liked a woman) (the ball saw a table)
 (the woman hit a man) (the ball liked a table)
 (a man saw the man) (a ball hit the man)
 (a man took the woman) (the woman took the man)
 (a man took a ball) (a man liked the man)
 (the woman hit the woman) (a man took the table)
 (a man took a woman) (the woman hit a ball)
 (a man saw the ball) (a man took a table) (a man saw a man)
 (a man liked the ball) (a man liked a man)
 (a man saw the woman) (the woman hit the table)
 (a man saw a ball) (the woman hit a woman)
 (a man liked the woman) (a man liked a ball)
 (a man saw the table) (a ball hit the ball)
 (a man saw a woman) (the woman took the ball)
 (a man liked the table) (a ball hit a man)
 (a man liked a woman) (the woman hit a table)
 (a man saw a table) (the woman took a man)
 (a man liked a table) (the woman saw the man)
 (a ball took the man) (the woman took the woman)
 (the woman took a ball) (the table hit the man)
 (a ball hit the woman) (the woman liked the man)
 (a ball hit a ball) (the woman took the table)
 (the woman took a woman) (the woman saw the ball)
 (the woman took a table) (the woman saw a man)
 (the woman liked the ball) (the woman liked a man)
 (a ball hit the table) (the woman saw the woman)
 (a ball hit a woman) (the woman saw a ball)
 (the woman liked the woman) (the woman liked a ball)
 (a ball took the ball) (the woman saw the table)
 (the woman saw a woman) (the table hit the ball)
 (a ball hit a table) (the woman liked the table)
 (a ball took a man) (the woman liked a woman)
 (the woman saw a table) (the table hit a man)
 (the woman liked a table) (a ball saw the man)
 (a woman hit the man) (a ball took the woman)
 (the table took the man) (a ball took a ball)
 (a ball liked the man) (the table hit the woman)
 (a ball took the table) (a ball took a woman)
 (the table hit a ball) (a table hit the man)
 (a ball saw the ball) (a ball took a table)
 (a ball saw a man) (a ball liked the ball)
 (a ball liked a man) (a ball saw the woman)
 (the table hit the table) (a ball saw a ball)
 (the table hit a woman) (a ball liked the woman)
 (a ball liked a ball) (a ball saw the table)
 (a woman hit the ball) (a ball saw a woman)
 (the table took the ball) (a ball liked the table)
 (a woman hit a man) (a ball liked a woman)
 (the table hit a table) (a ball saw a table)
 (the table took a man) (a ball liked a table)
 (a table hit the ball) (the table saw the man)
 (a table hit a man) (a woman took the man)
 (the table took the woman) (the table took a ball)
 (a table took the man) (a woman hit the woman)
 (the table liked the man) (a woman hit a ball)
 (the table took the table) (the table took a woman)
 (a table hit the woman) (the table saw the ball)
 (a table hit a ball) (the table took a table)
 (the table saw a man) (the table liked the ball)
 (the table liked a man) (a woman hit the table)
 (the table saw the woman) (a woman hit a woman)
 (the table saw a ball) (a table hit the table)
 (the table liked the woman) (the table liked a ball)
 (a table hit a woman) (a woman took the ball)
 (the table saw the table) (the table saw a woman)
 (a woman hit a table) (the table liked the table)
 (a woman took a man) (a table took the ball)
 (the table liked a woman) (the table saw a table)
 (a table hit a table) (the table liked a table)
 (a table took a man) (a woman saw the man)
 (a table saw the man) (a woman took the woman)
 (a woman took a ball) (a table took the woman)
 (a table took a ball) (a woman liked the man)
 (a woman took the table) (a table liked the man)
 (a woman took a woman) (a table took the table)
 (a table took a woman) (a woman saw the ball)
 (a woman took a table) (a woman saw a man)
 (a table saw the ball) (a table took a table)
 (a table saw a man) (a woman liked the ball)
 (a woman liked a man) (a table liked the ball)
 (a woman saw the woman) (a table liked a man)
 (a woman saw a ball) (a table saw the woman)
 (a table saw a ball) (a woman liked the woman)
 (a woman liked a ball) (a table liked the woman)
 (a woman saw the table) (a table liked a ball)
 (a woman saw a woman) (a table saw the table)
 (a table saw a woman) (a woman liked the table)
 (a woman liked a woman) (a woman saw a table)
 (a table liked the table) (a table liked a woman)
 (a table saw a table) (a woman liked a table)
 (a table liked a table))
> (run 1 (q) (sentence q))
((the man hit the man))
> (run 2 (q) (sentence q))
((the man hit the man) (the man hit the ball))
> (run 10000 (q) (sentence q))
((the man hit the man) (the man hit the ball)
 (the man hit a man) (the man took the man)
 (the ball hit the man) (the man hit the woman)
 (the man hit a ball) (the man hit the table)
 (the man hit a woman) (the man took the ball)
 (the man hit a table) (the ball hit the ball)
 (the man took a man) (the ball hit a man)
 (the man saw the man) (a man hit the man)
 (the man took the woman) (the man took a ball)
 (the ball took the man) (the man liked the man)
 (the man took the table) (the ball hit the woman)
 (the man took a woman) (the ball hit a ball)
 (the man saw the ball) (the man took a table)
 (the man saw a man) (the man liked the ball)
 (the man liked a man) (the man saw the woman)
 (the man saw a ball) (the ball hit the table)
 (the ball hit a woman) (the man liked the woman)
 (the man liked a ball) (the man saw the table)
 (a man hit the ball) (the man saw a woman)
 (the ball took the ball) (the man liked the table)
 (the man liked a woman) (a man hit a man)
 (the man saw a table) (the ball hit a table)
 (the ball took a man) (the man liked a table)
 (the ball saw the man) (a man took the man)
 (the ball took the woman) (the ball took a ball)
 (the woman hit the man) (a man hit the woman)
 (the ball liked the man) (a man hit a ball)
 (the ball took the table) (the ball took a woman)
 (the ball saw the ball) (the ball took a table)
 (the ball saw a man) (the ball liked the ball)
 (the ball liked a man) (a man hit the table)
 (the ball saw the woman) (a man hit a woman)
 (the ball saw a ball) (the ball liked the woman)
 (the ball liked a ball) (a man took the ball)
 (the ball saw the table) (the ball saw a woman)
 (the woman hit the ball) (a man hit a table)
 (the ball liked the table) (a man took a man)
 (the ball liked a woman) (the ball saw a table)
 (the woman hit a man) (the ball liked a table)
 (a man saw the man) (a ball hit the man)
 (a man took the woman) (the woman took the man)
 (a man took a ball) (a man liked the man)
 (the woman hit the woman) (a man took the table)
 (a man took a woman) (the woman hit a ball)
 (a man saw the ball) (a man took a table) (a man saw a man)
 (a man liked the ball) (a man liked a man)
 (a man saw the woman) (the woman hit the table)
 (a man saw a ball) (the woman hit a woman)
 (a man liked the woman) (a man liked a ball)
 (a man saw the table) (a ball hit the ball)
 (a man saw a woman) (the woman took the ball)
 (a man liked the table) (a ball hit a man)
 (a man liked a woman) (the woman hit a table)
 (a man saw a table) (the woman took a man)
 (a man liked a table) (the woman saw the man)
 (a ball took the man) (the woman took the woman)
 (the woman took a ball) (the table hit the man)
 (a ball hit the woman) (the woman liked the man)
 (a ball hit a ball) (the woman took the table)
 (the woman took a woman) (the woman saw the ball)
 (the woman took a table) (the woman saw a man)
 (the woman liked the ball) (the woman liked a man)
 (a ball hit the table) (the woman saw the woman)
 (a ball hit a woman) (the woman saw a ball)
 (the woman liked the woman) (the woman liked a ball)
 (a ball took the ball) (the woman saw the table)
 (the woman saw a woman) (the table hit the ball)
 (a ball hit a table) (the woman liked the table)
 (a ball took a man) (the woman liked a woman)
 (the woman saw a table) (the table hit a man)
 (the woman liked a table) (a ball saw the man)
 (a woman hit the man) (a ball took the woman)
 (the table took the man) (a ball took a ball)
 (a ball liked the man) (the table hit the woman)
 (a ball took the table) (a ball took a woman)
 (the table hit a ball) (a table hit the man)
 (a ball saw the ball) (a ball took a table)
 (a ball saw a man) (a ball liked the ball)
 (a ball liked a man) (a ball saw the woman)
 (the table hit the table) (a ball saw a ball)
 (the table hit a woman) (a ball liked the woman)
 (a ball liked a ball) (a ball saw the table)
 (a woman hit the ball) (a ball saw a woman)
 (the table took the ball) (a ball liked the table)
 (a woman hit a man) (a ball liked a woman)
 (the table hit a table) (a ball saw a table)
 (the table took a man) (a ball liked a table)
 (a table hit the ball) (the table saw the man)
 (a table hit a man) (a woman took the man)
 (the table took the woman) (the table took a ball)
 (a table took the man) (a woman hit the woman)
 (the table liked the man) (a woman hit a ball)
 (the table took the table) (the table took a woman)
 (a table hit the woman) (the table saw the ball)
 (a table hit a ball) (the table took a table)
 (the table saw a man) (the table liked the ball)
 (the table liked a man) (a woman hit the table)
 (the table saw the woman) (a woman hit a woman)
 (the table saw a ball) (a table hit the table)
 (the table liked the woman) (the table liked a ball)
 (a table hit a woman) (a woman took the ball)
 (the table saw the table) (the table saw a woman)
 (a woman hit a table) (the table liked the table)
 (a woman took a man) (a table took the ball)
 (the table liked a woman) (the table saw a table)
 (a table hit a table) (the table liked a table)
 (a table took a man) (a woman saw the man)
 (a table saw the man) (a woman took the woman)
 (a woman took a ball) (a table took the woman)
 (a table took a ball) (a woman liked the man)
 (a woman took the table) (a table liked the man)
 (a woman took a woman) (a table took the table)
 (a table took a woman) (a woman saw the ball)
 (a woman took a table) (a woman saw a man)
 (a table saw the ball) (a table took a table)
 (a table saw a man) (a woman liked the ball)
 (a woman liked a man) (a table liked the ball)
 (a woman saw the woman) (a table liked a man)
 (a woman saw a ball) (a table saw the woman)
 (a table saw a ball) (a woman liked the woman)
 (a woman liked a ball) (a table liked the woman)
 (a woman saw the table) (a table liked a ball)
 (a woman saw a woman) (a table saw the table)
 (a table saw a woman) (a woman liked the table)
 (a woman liked a woman) (a woman saw a table)
 (a table liked the table) (a table liked a woman)
 (a table saw a table) (a woman liked a table)
 (a table liked a table))
> (run 10000 (q) (sentence '(a woman liked a table)))
(_.0)
> (run 10000 (q) (sentence '(woman a liked a table)))
()
> (run 1 (x y) (sentence '(a ,x liked . ,y)))
()
> (run 1 (x y) (sentence `(a ,x liked . ,y)))
((man (the man)))
> (run 10 (x y) (sentence `(a ,x liked . ,y)))
((man (the man)) (man (the ball)) (man (a man)) (man (the woman))
  (man (a ball)) (man (the table)) (man (a woman))
  (man (a table)) (ball (the man)) (ball (the ball)))
> (run 1 (s)
    (fresh (x y z)
      (== `(,x ,y liked . ,z) s)
      (sentence s)))
((the man liked the man))
> (run 1 (s)
    (fresh (x y z)
      (== `(,x ,y liked . ,z) s)
      (absento 'man s)
      (sentence s)))
((the ball liked the ball))
> (run 1 (s)
    (fresh (x y z)
      (== `(,x ,y liked . ,z) s)
      (absento 'man s)
      (absento 'ball s)
      (sentence s)))
((the woman liked the woman))
> (run 1 (s)
    (fresh (np anything)
      (== `(,np . ,anything) s)
      (noun-phrase np)
      (sentence s)))
()
> (load "paip-1.scm")
> (run 1 (adj*)
    (Adj* adj*))
(())
> (run 2 (adj*)
    (Adj* adj*))
(())
> (run 1 (adj)
    (Adj adj))
(big)
> (run 2 (adj*)
    (Adj* adj*))
(() (big))
> (run 100 (adj*)
    (Adj* adj*))
(() (big) (little) (big big) (green) (big little)
 (little big) (big big big) (blue) (big green)
 (little little) (big big little) (green big)
 (big little big) (little big big) (big big big big)
 (adiabatic) (big blue) (little green) (big big green)
 (green little) (big little little) (little big little)
 (big big big little) (blue big) (big green big)
 (little little big) (big big little big) (green big big)
 (big little big big) (little big big big)
 (big big big big big) (adiabatic big) (big adiabatic)
 (little blue) (big big blue) (green green)
 (big little green) (little big green) (big big big green)
 (blue little) (big green little) (little little little)
 (big big little little) (green big little)
 (big little big little) (little big big little)
 (big big big big little) (big blue big) (adiabatic little)
 (little green big) (big big green big) (green little big)
 (big little little big) (little big little big)
 (big big big little big) (blue big big) (big green big big)
 (little little big big) (big big little big big)
 (green big big big) (big little big big big)
 (little big big big big) (big big big big big big)
 (adiabatic big big) (big adiabatic big) (little adiabatic)
 (big big adiabatic) (green blue) (big little blue)
 (little big blue) (big big big blue) (blue green)
 (big green green) (little little green)
 (big big little green) (green big green)
 (big little big green) (little big big green)
 (big big big big green) (big blue little) (adiabatic green)
 (little green little) (big big green little)
 (green little little) (big little little little)
 (little big little little) (big big big little little)
 (blue big little) (big green big little)
 (little little big little) (big big little big little)
 (green big big little) (big little big big little)
 (little big big big little) (big big big big big little)
 (adiabatic big little) (little blue big) (big big blue big)
 (green green big))
> 